name: Trigger PlayWrightTests Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo 2
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/KuzinYD/PlaywrightTests/actions/workflows/trigger-tests.yml/dispatches \
            -d '{"ref":"main"}'
