name: Trigger Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      target_branch:
        description: 'Branch to trigger the workflow on'
        required: false
        default: 'main'

permissions:
  contents: write  # Explicitly grant write permissions to the workflow

jobs:
  trigger-external-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository_dispatch event
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const response = await github.rest.repos.createDispatchEvent({
                owner: 'KuzinYD',  //
